{
 "title": "Member specific",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player_id",
    "query": "SELECT CAST(ranking.player.id AS CHAR) FROM ranking.player ORDER BY CAST(ranking.player.id AS CHAR) ASC"
   },
   { "name": "season", "query": "SELECT Season FROM game" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "player_id" },
  {
   "title": "Player Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  ranking.player.player_name\nFROM\n  ranking.player\nWHERE\n  CAST(ranking.player.id AS CHAR) = ${player_id}"
    }
   ]
  },
  {
   "title": "Character Tracking",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  ranking.fighter.fighter_name,\n  COUNT(ranking.fighter.fighter_name)\nFROM\n  ranking.game\n  LEFT JOIN ranking.fighter on ranking.game.fighter_id_1 = ranking.fighter.id\nWHERE\n  CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n  AND game.Season LIKE ${season}\nGROUP BY\n  ranking.fighter.fighter_name"
    }
   ]
  },
  {
   "title": "Played Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  SUM(ranking.game.wins) + SUM(ranking.game.loses)\nFROM\n  ranking.game\nWHERE\n  CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n  AND game.Season LIKE ${season}"
    }
   ]
  },
  {
   "title": "Played Sets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  COUNT(ranking.game.player_id)\nFROM\n  ranking.game\nWHERE\n  CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n  AND game.Season LIKE ${season}"
    }
   ]
  },
  {
   "title": "Played Tournaments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  COUNT(t.tournament_date) as tournament_count\nFROM\n  (\n    SELECT\n      DISTINCT DATE(ranking.game.time_created) AS tournament_date\n    FROM\n      ranking.game\n    WHERE\n      CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n      AND game.Season LIKE ${season}\n  ) AS t"
    }
   ]
  },
  {
   "title": "Won Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  SUM(ranking.game.wins)\nFROM\n  ranking.game\nWHERE\n  CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n  AND game.Season LIKE ${season}"
    }
   ]
  },
  {
   "title": "Lost Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  SUM(ranking.game.loses)\nFROM\n  ranking.game\nWHERE\n  CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n  AND game.Season LIKE ${season}"
    }
   ]
  },
  {
   "title": "Win Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  (SUM(game.wins) / SUM(game.wins + game.loses)) * 100 AS win_percentage\nFROM\n  ranking.game\nWHERE\n  CAST(ranking.game.player_id AS CHAR) LIKE ${player_id}\n  AND game.Season LIKE ${season}"
    }
   ]
  }
 ]
}