{
 "title": "Ranking",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "season", "query": "SELECT Season FROM game" }
  ]
 },
 "panels": [
  {
   "title": "Wins - Loses",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  player.player_name,\n  SUM(game.wins) AS wins,\n  SUM(game.loses) AS losses\nFROM\n  game\n  LEFT JOIN player ON game.player_id = player.id\nWHERE\n  game.Season LIKE ${season}\nGROUP BY\n  player.player_name\nORDER BY\n  wins DESC,\n  losses DESC"
    }
   ]
  },
  {
   "title": "Win rate",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  player.player_name,\n  (SUM(game.wins) / SUM(game.wins + game.loses)) * 100 AS win_percentage\nFROM\n  game\n  LEFT JOIN player ON game.player_id = player.id\nWHERE\n  game.Season LIKE ${season}\nGROUP BY\n  player.player_name\nORDER BY\n  win_percentage DESC;"
    }
   ]
  },
  {
   "title": "Last sets",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  game.id,\n  player.player_name,\n  game.wins,\n  game.loses\nFROM\n  game\n  LEFT JOIN player ON game.player_id = player.id\nWHERE\n  game.Season LIKE ${season}\nORDER BY\n  game.id DESC"
    }
   ]
  },
  {
   "title": "ALL PLAYERS",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  player.player_name\nFROM\n  player"
    }
   ]
  },
  {
   "title": "ALL FIGHTERS",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "dataset": "mysql", "rawSql": "SELECT\n  *\nFROM\n  fighter" }
   ]
  }
 ]
}