[package]
name = "actix-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
mysql = "25.0.0"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"
env_logger = "0.11.3"
actix-files = "0.6.5"
